"""Build the descriptive three-season comparison from validated season outputs."""

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESEARCH = ROOT / "docs/research"
INPUTS = [
    "2026-09-06-l2m-2023-24-results.json",
    "2026-09-06-l2m-2024-25-results.json",
    "2026-09-06-l2m-season-results.json",
]


def main():
    results, inputs = [], []
    for filename in INPUTS:
        path = RESEARCH / filename
        raw = path.read_bytes()
        result = json.loads(raw)
        coverage = result["coverage"]
        if not (coverage["indexed"] == coverage["retrieved"] == coverage["joined_crews"]) or coverage["unmatched"]:
            raise ValueError(f"Incomplete report or assignment coverage: {filename}")
        inputs.append({"path": str(path.relative_to(ROOT)), "sha256": hashlib.sha256(raw).hexdigest()})
        results.append(result)
    secondary_path = RESEARCH / "2026-09-06-referee-season-secondary.json"
    inputs.append({"path": str(secondary_path.relative_to(ROOT)),
                   "sha256": hashlib.sha256(secondary_path.read_bytes()).hexdigest()})
    secondary = {row["season"]: row for row in json.loads(secondary_path.read_text())["seasons"]}
    phase_rows, integrity, categories = [], [], []
    for result in results:
        season = result["season"]
        for phase, counts in sorted(result["phases"].items()):
            grades = counts["grades"]
            phase_rows.append({"season": season, "phase": phase, **counts,
                               "missed_share_pct": round(100 * grades.get("INC", 0) / counts["errors"], 2) if counts["errors"] else None,
                               "games_with_error_pct": round(100 * counts["games_with_error"] / counts["games"], 2),
                               "assessments_per_represented_period": round(counts["assessments"] / counts["reviewed_periods"], 4)})
        trios = [r for r in result["exact_trios"] if r["phase"] == "regular_season"]
        officials = [r for r in result["official_assignment_exposure"] if r["phase"] == "regular_season"]
        integrity.append({"season": season, "indexed_reports": result["coverage"]["indexed"],
                          "joined_reports": result["coverage"]["joined_crews"],
                          "errors_all_phases": result["total"]["errors"],
                          "assessments_all_phases": result["total"]["assessments"],
                          "beneficiary_mismatched_games": len(result["beneficiary_audit"]["mismatched_games"]),
                          "explicit_error_beneficiaries": result["beneficiary_audit"]["explicit_error_beneficiaries"],
                          "summary_beneficiaries": sum(result["beneficiary_audit"]["raw_source_summary_totals"].values()),
                          "reviewed_duplicate_pairs": sum(len(r["pairs"]) for r in result.get("duplicate_assessment_audit", [])),
                          "regular_season_trios": len(trios), "trios_seen_once": sum(r["games"] == 1 for r in trios),
                          "max_trio_games": max(r["games"] for r in trios), "officials": len(officials)})
        categories.extend({"season": season, **row} for row in result["call_types"])
    output = {"protocol": "ml/l2m_three_season_extension.md", "inputs": inputs,
              "total_reports": sum(r["coverage"]["indexed"] for r in results),
              "phase_comparisons": phase_rows, "coverage_and_integrity": integrity,
              "call_categories": categories,
              "secondary_regular_season_context": [secondary[r["season"]] for r in results],
              "limits": ["Indexed selected L2M samples, not full-game officiating accuracy.",
                         "Changes in replay scope and game mix prevent causal interpretation.",
                         "Two 2024-25 identical CC row pairs retained with reviewed source exceptions.",
                         "Beneficiary summaries fail integrity checks in all three seasons."]}
    (RESEARCH / "2026-09-06-l2m-three-season-comparison.json").write_text(json.dumps(output, indent=2) + "\n")
    lines = [
        "# Three seasons of NBA L2M data", "",
        "Generated by `ml/compare_l2m_seasons.py` from validated season results; see the companion [study](2026-09-06-l2m-three-season-study.md).", "",
        "## Regular-season comparison", "",
        "| Season | Reports | Represented periods | IC | INC | Errors | Errors/game | Errors/period | INC share of errors | Reports with IC/INC |", 
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for row in phase_rows:
        if row["phase"] == "regular_season":
            lines.append(f'| {row["season"]} | {row["games"]} | {row["reviewed_periods"]} | {row["grades"].get("IC", 0)} | {row["grades"].get("INC", 0)} | {row["errors"]} | {row["errors_per_game"]:.3f} | {row["errors_per_reviewed_period"]:.3f} | {row["missed_share_pct"]:.1f}% | {row["games_with_error"]} ({row["games_with_error_pct"]:.1f}%) |')
    lines += ["", "## Other phases, kept separate", "",
              "| Season | Phase | Reports | IC | INC | Errors | Errors/period |",
              "|---|---|---:|---:|---:|---:|---:|"]
    for row in phase_rows:
        if row["phase"] != "regular_season":
            lines.append(f'| {row["season"]} | {row["phase"]} | {row["games"]} | {row["grades"].get("IC", 0)} | {row["grades"].get("INC", 0)} | {row["errors"]} | {row["errors_per_reviewed_period"]:.3f} |')
    lines += ["", "## Coverage and integrity", "",
              "| Season | Indexed and joined reports | All-phase errors | Source beneficiary total | Mismatched summaries | Ungraded rows | Reviewed duplicate pairs |",
              "|---|---:|---:|---:|---:|---:|---:|"]
    for row, result in zip(integrity, results):
        lines.append(f'| {row["season"]} | {row["indexed_reports"]} | {row["errors_all_phases"]} | {row["summary_beneficiaries"]} | {row["beneficiary_mismatched_games"]} | {result["total"]["grades"].get("ungraded", 0)} | {row["reviewed_duplicate_pairs"]} |')
    lines += ["", "Raw report rows are retained. Identical correct-call pairs in 2024–25 do not alter error totals; removing one from each pair would lower only CC/assessment totals by two. Represented periods are distinct period labels containing assessment rows, not independently measured minutes. No team-benefit rankings or individual error attribution are inferred.", "",
              "## All regular-season error categories", "",
              "| Raw NBA category | 2023–24 | 2024–25 | 2025–26 |", "|---|---:|---:|---:|"]
    lookup = {(r["season"], r["call_type"]): r["errors"] for r in categories if r["phase"] == "regular_season"}
    kinds = sorted({kind for (season, kind), errors in lookup.items() if errors})
    for kind in kinds:
        lines.append("| " + kind + " | " + " | ".join(str(lookup.get((r["season"], kind), 0)) for r in results) + " |")
    lines += ["", "## Cached regulation foul context", "",
              "| Season | Cached games | Foul events/game | Technical events/game |",
              "|---|---:|---:|---:|"]
    for result in results:
        row = secondary[result["season"]]
        lines.append(f'| {row["season"]} | {row["games"]} | {row["fouls_per_game"]:.2f} | {row["technicals_per_game"]:.3f} |')
    lines += ["", "These ESPN regulation counts cover a different population from L2M and are not possession-adjusted or a measure of correctness.", ""]
    (RESEARCH / "2026-09-06-l2m-three-season-comparison.md").write_text("\n".join(lines))
    print(json.dumps({"reports": output["total_reports"], "integrity": integrity}))


if __name__ == "__main__":
    main()
