"""Assemble every referee result into one report, generated from the result JSONs.

Nothing here is hand-typed: each figure is read from the artifact the analysis wrote, so the
report cannot drift from the run that produced it.

Sources:
    ml/data/referee/axes_results.json         ml/referee_axes.py            (ADR 0007 axes A, C)
    ml/data/referee/player_axes_results.json  ml/referee_player_axes.py     (axes D1, D2, D2-OOS, D3)
    ml/data/referee/exploratory_results.json  ml/referee_exploratory_axes.py (axes B, E, F, D gate)
    ml/data/referee/makeup_diagnostic.json    ml/referee_makeup_diagnostic.py

Usage:
    ml/.venv/bin/python ml/referee_report.py
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

DATA_DIR = Path("ml/data/referee")
OUT = Path("ml/REFEREE_PLAYER_REPORT.md")

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)


def load(name: str) -> dict:
    path = DATA_DIR / name
    return json.loads(path.read_text()) if path.exists() else {}


def verdict(p: float | None, ratio: float | None) -> str:
    if p is None:
        return "—"
    if p < 0.01:
        return f"**real** (p={p:.4f}, spread x{ratio:.2f})"
    if p < 0.05:
        return f"suggestive, fails the p<0.01 gate (p={p:.4f})"
    return f"null (p={p:.4f})"


def main() -> None:
    axes = load("axes_results.json")
    player = load("player_axes_results.json")
    expl = load("exploratory_results.json")
    mk = load("makeup_diagnostic.json")
    po = load("playoff_claims.json")
    conf = load("playoff_confound.json")

    L: list[str] = []
    w = L.append

    w("# Referees — every axis, measured")
    w("")
    w("Generated by `ml/referee_report.py`. Pre-registrations:")
    w("[ADR 0007](../docs/adr/0007-referee-analysis-axes-are-pre-registered.md) for axes A/B/C, "
      "`ml/referee_player_preregistration.md` (and its 2026-08-21 amendment) for D, E and F.")
    w("")
    corpus = player.get("corpus", {})
    w(f"**Corpus.** {axes.get('n_games', 0):,} regular-season games with three named officials, a "
      f"play stream and a box score; {axes.get('n_fouls', 0):,} foul plays; "
      f"{corpus.get('player_games', 0):,} player-games. Seasons "
      f"{corpus.get('seasons', ['?'])[0]} … {corpus.get('seasons', ['?'])[-1]}. "
      f"The postseason was added on 2026-08-21 — **{po.get('playoff_games', 0)} playoff games** over "
      "the same seasons, fetched by `scripts/fetch_playoff_officials.ts`, and reported in its own "
      "section below. Every regular-season figure above and below excludes it.")
    w("")
    w("*Correction, 2026-08-21.* An earlier run filtered on exactly three listed officials, which "
      "silently dropped the 295 regular-season and 309 playoff games where ESPN also lists a "
      "standby fourth. The filter is now `>= 3` and the working crew is the first three by "
      "`order`; every figure here is the corrected run.")
    w("")
    w("Every test asks the same question first: does the official dimension carry more variance "
      "than a permutation null in which each official's games are a random draw from the same "
      "seasons? That global test is multiplicity-free, and under the pre-registration **no named "
      "figure may be published from an axis whose global test does not clear p < 0.01**.")
    w("")
    w("Three officials work every game and the play stream never records which one blew the "
      "whistle, so every per-official figure below is roughly **a third** of the effect it names.")

    # ---------------- what is real
    w("")
    w("## What is real")
    w("")
    w("| finding | league | spread vs null | verdict |")
    w("|---|---|---|---|")
    for group, col, label, unit in (
        ("volume", "vol_total", "Officials differ in how much they whistle", "fouls/game"),
        ("volume", "vol_looseBall", "…and most of all in loose-ball fouls", "fouls/game"),
        ("axis_c", "C_q1_share", "Officials differ in how much lands in Q1", "share of game"),
        ("axis_a", "A_total_diff", "Officials differ in home tilt", "away−home fouls/game"),
    ):
        g = axes.get(group, {}).get(col, {}).get("global")
        if not g:
            continue
        offs = axes[group][col]["officials"]
        vals = [v["mean"] for v in offs.values()]
        w(f"| {label} | {g['league_mean']:.3f} {unit} | x{g['spread_ratio']:.2f} "
          f"(range {min(vals):.3f}–{max(vals):.3f}) | {verdict(g['p_value'], g['spread_ratio'])} |")
    b = expl.get("axis_b", {})
    if b:
        g = b["per_official"]["global"]
        w(f"| Fouls tilt toward the leading team as the lead grows | "
          f"{b['league_mean']:.4f} of fouls on the leader | x{g['spread_ratio']:.2f} | "
          f"{verdict(g['p_value'], g['spread_ratio'])} |")
    if b:
        w("")
        w("The lead-size gradient, which is the largest effect anywhere in this report:")
        w("")
        w("| lead | fouls called on the team that is ahead |")
        w("|---|---|")
        for k, v in b["by_lead_size"].items():
            w(f"| {k} points | {v['pro_trailing']*100:.2f}% ({v['n']:,} fouls) |")
        w("")
        w("**This is not evidence of a whistle.** A trailing team attacks the rim and a leading "
          "team protects its lead, so the foul follows the basketball. The gradient is reported "
          "because it is large and real, not because it is a referee effect.")

    # ---------------- what is not
    w("")
    w("## What is not")
    w("")
    w("| claim | test | result |")
    w("|---|---|---|")
    c = axes.get("axis_c", {}).get("C_q4_last2", {}).get("global")
    if c:
        w(f"| Officials swallow the whistle late | fouls in the last 2:00 of Q4, per official | "
          f"{verdict(c['p_value'], c['spread_ratio'])} |")
    if player.get("d3"):
        g = player["d3"]["star_early2"]["global"]
        w(f"| Some officials put stars in early foul trouble | share of star-games with 2+ fouls "
          f"in Q1 | {verdict(g['p_value'], g['spread_ratio'])} |")
        gh = player["d3"]["star_early2_home"]["global"]
        gr = player["d3"]["star_early2_road"]["global"]
        w(f"| …and it depends on home vs road | same, split by venue | "
          f"home {verdict(gh['p_value'], gh['spread_ratio'])}; road {verdict(gr['p_value'], gr['spread_ratio'])} |")
    gate = expl.get("d_gate", {})
    for key, label in (("d1", "Officials have it in for particular players (fouls)"),
                       ("d2", "Officials have it in for particular players (wins)")):
        g = gate.get(key)
        if g:
            w(f"| {label} | spread of z across {g['n_pairs']:,} pairs, full-grid permutation | "
              f"{verdict(g['p_value'], g['observed_sd_z']/g['null_sd_z_mean'])} |")
    e = expl.get("axis_e", {})
    if e:
        d = e["dose_response"]
        w(f"| The home whistle needs a crowd | away foul share on log(attendance), season fixed | "
          f"t={d['t']:+.2f} — null |")

    # ---------------- the famous claims
    oos = player.get("d2_oos", {})
    if oos:
        w("")
        w("## The famous claims, named before they were measured")
        w("")
        w(f"Split at **{oos['split_season']}**: every claim below was in public circulation by then, "
          f"so seasons from {oos['split_season']} on are an out-of-sample test of a claim that was "
          f"found by looking. A pair with fewer than {oos['min_games']} out-of-sample games is "
          "reported untestable rather than given a verdict.")
        w("")
        w("| claim | era | record | expected | difference | z |")
        w("|---|---|---|---|---|---|")
        for c in oos["claims"]:
            for era, lab in (("in_sample", "before split"), ("out_of_sample", "out-of-sample"), ("all", "all")):
                e_ = c.get(era, {})
                if not e_.get("games"):
                    continue
                z = f"{e_['z']:+.2f}" if e_.get("z") is not None else "—"
                note = "" if e_.get("testable") else " ⚠︎"
                name = f"**{c['official']} × {c['player']}**" if era == "in_sample" else ""
                w(f"| {name} | {lab}{note} | {e_['wins']}–{e_['losses']} | "
                  f"{e_['expected_wins']:.2f} W | {e_['wins_above_expected']:+.2f} W | {z} |")
        w("")
        w("⚠︎ = fewer than the pre-registered minimum of out-of-sample games.")

    # ---------------- playoffs
    if po and conf:
        sw = conf.get("sweep_opponent_aware", {})
        w("")
        w("## The playoffs, where the legends actually live")
        w("")
        w(f"The five pairs were named in the pre-registration and committed **before "
          f"`scripts/fetch_playoff_officials.ts` existed**, so the claim list could not have been "
          f"chosen with any sight of these numbers. Expectation here is opponent-aware: a win model "
          f"fitted on all {conf['model']['n_team_games']:,} playoff team-games from each side's "
          f"regular-season strength and home court, because senior officials draw later rounds "
          f"against better teams and that alone would manufacture losing records.")
        w("")
        w("| claim | playoff record | expected | difference | p | opponent strength with / without |")
        w("|---|---|---|---|---|---|")
        for c in conf["claims"]:
            w(f"| {c['official']} × {c['player']} | {c['wins']}–{c['losses']} | "
              f"{c['expected_wins_opponent_aware']:.2f} W | {c['wins_above_expected']:+.2f} W | "
              f"{c['p_at_or_below']:.4f} | {c['mean_opponent_strength_with']:.3f} / "
              f"{c['mean_opponent_strength_without']:.3f} |")
        w("")
        w("Four of the five are nothing, and Brothers × Durant runs the *opposite* way. The fifth "
          "is not nothing.")
        if sw:
            w("")
            cp0 = conf["claims"][0]
            w(f"**Chris Paul's teams went {cp0['wins']}–{cp0['losses']} in playoff games Scott "
              f"Foster worked**, against {cp0['expected_wins_opponent_aware']:.2f} "
              f"expected. His games with Foster were not harder than his other playoff games "
              f"(opponent strength {cp0['mean_opponent_strength_with']:.3f} against "
              f"{cp0['mean_opponent_strength_without']:.3f}), so the assignment "
              f"explanation does not cover it. Across every playoff pair with at least "
              f"{sw['min_games']} shared games it ranks **#{sw['foster_paul_rank']} of "
              f"{sw['n_pairs']:,}** — the single most lopsided official-and-player record in eleven "
              "postseasons.")
            w("")
            w("**And that is exactly the problem.** Somebody has to be first:")
            w("")
            w(f"- The most extreme p-value {sw['n_pairs']:,} pairs of pure noise would produce is "
              f"**{sw['expected_min_p']}**. Foster × Paul comes in at **{sw['ranked'][0]['p_two_sided']:.4f}** "
              "— barely past what the maximum of nothing looks like.")
            w(f"- {sw['n_p_under_01']} pairs clear p < 0.01. Chance predicts {sw['expected_under_01']}.")
            w(f"- {sw['n_p_under_05']} clear p < 0.05. Chance predicts {sw['expected_under_05']} — "
              "there are *fewer* than there should be.")
            w("")
            w("| official | player | record | expected | p |")
            w("|---|---|---|---|---|")
            for t in sw["ranked"][:8]:
                w(f"| {t['official']} | {t['player']} | {t['wins']}/{t['games']} | "
                  f"{t['expected']:.2f} | {t['p_two_sided']:.4f} |")
            w("")
            w("Scott Foster appears five times in that list and **four of them are teams winning** "
              "— Miles McBride, Josh Hart, OG Anunoby and Mitchell Robinson all went roughly "
              "ten-and-one with him. The same official is a curse for one star and a charm for four "
              "others, which is what a large grid of coin flips looks like from close up.")
        claims = {(c["official"], c["player"]): c for c in po.get("claims", [])}
        cp = claims.get(("Scott Foster", "Chris Paul"))
        if cp:
            ins, oos = cp.get("playoffs_in_sample", {}), cp.get("playoffs_out_of_sample", {})
            w("")
            w("**The one test that would settle it cannot be run.** The claim was in circulation by "
              f"2019-20. Before that split Paul was {ins.get('wins', 0)}–{ins.get('losses', 0)} with "
              f"Foster; after it, {oos.get('wins', 0)}–{oos.get('losses', 0)}. The direction holds, "
              "but both halves fall under the pre-registered minimum of "
              f"{po['min_playoff_pair_games']} games, so **neither is testable** and no verdict is "
              "drawn from either. A claim the public found by looking can only be confirmed by "
              "games nobody had seen when they found it, and there are five of those.")

    # ---------------- make-up calls
    f = expl.get("axis_f", {})
    if f and mk:
        w("")
        w("## Make-up calls: a t = 27 result, killed by its own mechanism test")
        w("")
        w(f"Consecutive fouls switch teams **{f['observed_switch_rate']*100:.2f}%** of the time "
          f"against **{f['null_switch_rate']*100:.2f}%** from a shuffle that holds each team's foul "
          f"total fixed — an excess of {f['excess']*100:+.2f} points at t={f['excess_t']:+.1f}, "
          f"rising to {f['quick_excess']*100:+.2f} points for calls under "
          f"{f['quick_window_sec']} seconds apart. On its own that reads as compensation.")
        w("")
        w("It is not. That null destroys the possession structure, and basketball alternates "
          "possessions. The test that separates the two uses the case where they predict "
          "**opposite signs**: an offensive foul is a turnover, so the fouling team goes straight "
          "onto defense and mechanics predicts the next foul lands on *them* — below chance — "
          "while compensation still predicts above.")
        w("")
        w("| first foul | next foul switches teams | null | excess | t |")
        w("|---|---|---|---|---|")
        for key, lab in (("defensive", "defensive (ball changes hands)"),
                         ("offensive", "**offensive (turnover)**")):
            v = mk["by_first_foul"].get(key)
            if v and "observed_switch" in v:
                w(f"| {lab} | {v['observed_switch']*100:.2f}% | {v['null_switch']*100:.2f}% | "
                  f"{v['excess']*100:+.2f} pp | {v['t']:+.1f} |")
        v = mk.get("offensive_by_gap", {}).get("0-15s")
        if v and "observed_switch" in v:
            w(f"| offensive, within 15 seconds | {v['observed_switch']*100:.2f}% | "
              f"{v['null_switch']*100:.2f}% | {v['excess']*100:+.2f} pp | {v['t']:+.1f} |")
        w("")
        same = 100 - v["observed_switch"] * 100 if v and "observed_switch" in v else None
        w("The sign flips exactly where possession says it should, and within fifteen seconds of an "
          f"offensive foul the next whistle goes against the **same team {same:.0f}% of the time**. "
          "**The alternation is the ball changing hands, not the referee evening things up.**")
        w("")
        w("The excess by gap, which traces the possession clock rather than any human intention:")
        w("")
        w("| gap between calls | excess over the shuffled null |")
        w("|---|---|")
        for k, v in mk.get("by_gap", {}).items():
            if "excess" in v:
                w(f"| {k} | {v['excess']*100:+.2f} pp (t={v['t']:+.1f}) |")

    # ---------------- crowd
    if e:
        w("")
        w("## Does the home whistle need a crowd?")
        w("")
        w("2020-21 is the experiment: one season, one rulebook, one set of officials, with and "
          "without an audience.")
        w("")
        w("| games | n | away share of fouls | away − home |")
        w("|---|---|---|---|")
        for key in ("no_attendance_reported", "attendance_reported", "small_crowd_under_3000", "crowd_3000_plus"):
            v = e["within_2020_21"][key]
            w(f"| {v['label']} | {v['n']:,} | {v['away_share']:.4f} | {v['diff']:+.3f} |")
        for key in ("restart", "same_season_normal"):
            v = e["restart_2019_20"][key]
            w(f"| 2019-20 {v['label']} | {v['n']:,} | {v['away_share']:.4f} | {v['diff']:+.3f} |")
        v = e["all_games"]
        w(f"| every game, all seasons | {v['n']:,} | {v['away_share']:.4f} | {v['diff']:+.3f} |")
        w("")
        d = e["dose_response"]
        w(f"One comparison suggests the whistle needs an audience and two do not. The 2019-20 "
          f"restart shows no gap at all, and across all {d['n']:,} games with an attendance "
          f"figure, doubling the crowd moves the away foul share by "
          f"{d['interpretation_pp_per_doubling']:+.3f} points at t={d['t']:+.2f}. "
          "**Read as a null**, with the caveat that a missing attendance field is being treated "
          "as an empty building, which is an inference rather than a fact.")

    OUT.write_text("\n".join(L) + "\n")
    log.info("wrote %s (%d lines)", OUT, len(L))


if __name__ == "__main__":
    main()
