/**
 * Home win rates in the games where the home team had travelled in too.
 *
 * Generated by `scripts/measure_home_rest_confound.ts` into `ml/home_rest_confound_facts.json`
 * and mirrored here by hand; `home-rest-confound-facts.test.ts` fails when the two differ. The
 * method page printed these as typed prose until 2026-10-11, and one of them went stale after a
 * stored-score correction with nothing to notice.
 */
export const HOME_REST_CONFOUND = Object.freeze({
  population: 47143,
  bothTravelledIn: Object.freeze({ games: 23076, homeWinPct: 59.7 }),
  homeFlewFarther: Object.freeze({ games: 12492, homeWinPct: 59.9 }),
  homeTravelledInOnBackToBack: Object.freeze({ games: 5948, homeWinPct: 58 }),
});
