"""Rebuild review-only HTML from bundled source snapshots; no production data is written."""
from pathlib import Path
import json,html
P=Path(__file__).parent
load=lambda n:json.loads((P/'data'/f'{n}.json').read_text())
s=load('season')['data'];q=load('schedule')['data'];g=load('games')['data'];a=load('analysis')['data'];p=load('player-rest')
e=html.escape
fmt=lambda v:f'{v:,}'
sign=lambda v:f'{v:+.1f}'
nav=[('games','Games'),('season','Season Report'),('schedule','Schedule Edge'),('explore','Explore')]
def doc(slug,title,content,dark=False):
 if slug in ['games','season','shooting']:
  content=content.replace('<h3>','<h2 class="minor">').replace('</h3>','</h2>')
 links=''.join(f'<a href="{n}.html" class="{"active" if n==slug else ""}">{t}</a>' for n,t in nav)
 text=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} · FullCourt design review</title><link rel="stylesheet" href="styles.css"><body class="{'dark home' if dark else ''}"><aside class="review" aria-label="Design review">Design review · real data snapshot · <a href="index.html">All mockups</a></aside><header class="top"><a class="brand" href="home.html">FULL<span>COURT</span></a><nav aria-label="Primary">{links}</nav><a class="reference" href="methods.html">Behind the Data ↗</a></header><main class="container">{content}</main><footer class="footer"><a href="methods.html">Behind the Data</a><a href="about.html">About FullCourt</a><a href="NOTES.md">Snapshot sources</a><span class="end">NBA rest, travel & schedule research</span></footer><nav class="mobile-nav" aria-label="Mobile primary">{links}</nav><script src="review.js"></script></body></html>'''
 (P/f'{slug}.html').write_text(text)
def head(title,desc,eyebrow,season=True):
 return f'<div class="page-head"><div><div class="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{desc}</p></div>'+('''<div class="season-control"><label class="eyebrow" for="season">Season snapshot</label><select id="season"><option>2025–26</option></select><div class="scope">Data through Apr 12, 2026</div></div>''' if season else '')+'</div>'
def table(headers,rows):return '<div class="scroll" tabindex="0" role="region" aria-label="Detailed data table"><table><thead><tr>'+''.join(f'<th scope="col">{x}</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join(f'<td>{x}</td>' for x in r)+'</tr>' for r in rows)+'</tbody></table></div>'
def disclosure(title,body):return f'<details class="disclosure"><summary>{title}</summary><div>{body}</div></details>'
base=a['venueBaseline']['homeWinPct'];widest=next(x for x in a['thresholds'] if x['threshold']==7);edge=widest['winPct']-base
home=f'''<section class="hero"><div><div class="eyebrow">NBA rest · travel · schedule</div><h1>Rest is a stat.</h1><p>Days off, miles traveled, and games played close together. See how teams arrive—and what the results say.</p><a class="button primary" href="games.html">Explore games <span aria-hidden="true">→</span></a></div><div class="hero-aside">One team played <strong>last night.</strong><br>The other had <strong>three days off.</strong></div></section>
<section class="section finding"><div><div class="eyebrow">Across NBA history · 1985–86 to 2025–26</div><h2>A rest gap, measured against home court.</h2><div class="big num rest">+{edge:.1f}<span style="font-size:24px;letter-spacing:0"> pp</span></div><p class="caption">Above the home win-rate baseline in {fmt(widest['games'])} games with the widest modeled rest gaps (RA ≥ 7).</p></div><div><div class="bar-label"><span>Home teams overall</span><b class="num">{base}%</b></div><div class="bar-track"><div class="bar-fill" style="width:{base}%;background:var(--muted)"></div></div><div class="bar-label"><span>Rested home team · widest gap</span><b class="num rest">{widest['winPct']}%</b></div><div class="bar-track"><div class="bar-fill" style="width:{widest['winPct']}%"></div></div><p class="caption">Bars run from 0–100%. Baseline: {fmt(a['venueBaseline']['games'])} games. These historical groups differ in more than rest; this is an association, not a causal estimate.</p><p style="margin-top:20px"><a href="http://localhost:3110/analysis">Read the model results →</a></p></div></section>
<section class="section two support"><article><div class="eyebrow">The schedule · 2025–26</div><h2>Some teams get more favorable matchups.</h2><div class="bar-label"><span>Utah</span><strong class="num rest">+21 net edge games</strong></div><div class="bar-label"><span>Boston</span><strong class="num tired">−17 net edge games</strong></div><p>Favorable minus unfavorable games. {fmt(q['league']['countedGames'])} of {fmt(q['scheduledGames'])} games compared; this is a schedule comparison, not a prediction of wins.</p><a href="schedule.html">Compare team schedules →</a></article><article><div class="eyebrow">The players · shooting by rest</div><h2>Does a fresh player shoot better?</h2><p>Compare no-rest shooting with three or more days off, with attempts beside every rate. A large single-season gap can still be uncertain.</p><p class="small">Regular-season player coverage: 1996–97 to 2025–26. Career estimates pool attempts and shrink uncertain differences.</p><a href="shooting.html">Look up a player →</a></article></section>
<div class="discover"><div><h3>More questions from the court.</h3><p class="muted">Playoff workload and other basketball studies.</p></div><a href="explore.html">Explore the research →</a></div>'''
doc('home','Rest is a stat',home,True)

def game_row(x):
 adv=x['restAdvantage'];side=adv['advantageTeam'];team=x['homeTeam'] if side=='home' else x['awayTeam'];diff=abs(adv['differential']);detail=''
 for k,label in [('away','Away'),('home','Home')]:
  f=x[k+'Fatigue'];t=x[k+'Team'];detail+=f'<div><h3>{e(t["name"])} <span class="small muted">{label}</span></h3>'
  for key,lab in [('daysRest','Days rest'),('score','Fatigue score'),('gamesInLast7Days','Games in last 7 days'),('travelDistanceMiles','Estimated travel · miles')]:detail+=f'<div class="detail-metric"><span>{lab}</span><span class="num">{fmt(f[key]) if f[key] is not None else "—"}</span></div>'
  detail+='</div>'
 return f'''<details class="game"><summary><span class="game-status eyebrow">Final<br><span class="muted">{e(x['tipOffEt'])}</span></span><div>{''.join(f'<div class="game-team"><span class="team-mark">{x[k+"Team"]["abbreviation"]}</span><span>{e(x[k+"Team"]["name"])}</span><strong class="num">{x[k+"Score"]}</strong></div>' for k in ['away','home'])}</div><div class="edge"><span class="small muted">Rest advantage</span><br><b class="num rest">{team['abbreviation']} {diff:.1f}</b></div><span aria-hidden="true">⌄</span></summary><div class="game-detail"><div class="two">{detail}</div><p class="caption">Schedule context for this game. A rest advantage is not a win probability.</p></div></details>'''
games=head('Games','Rest, travel, and workload for each matchup.','The matchup board')+'''<div class="status"><span>2025–26 regular season complete · final day</span><a href="states.html#upcoming">View upcoming season →</a></div><div class="toolbar"><strong>Sunday, April 12, 2026</strong><span class="muted small">Historical snapshot · date browsing comes in the application</span></div><div class="board"><section aria-label="Matchups">'''+''.join(game_row(x) for x in g)+f'''</section><aside><div class="eyebrow">On this date</div><div class="metric num">{len(g)} <span class="small muted">games</span></div><p class="muted">Open a matchup to compare its workload details.</p><section class="section"><h3>How the gap is calculated</h3><p class="caption">Both teams use the same fatigue model. The difference includes rest, travel and schedule density.</p><p style="margin-top:16px"><a href="methods.html">Read the method →</a></p></section><section class="section"><h3>Edges ahead</h3><p class="caption">Upcoming projections are separate from this completed slate.</p><a href="states.html#upcoming">Upcoming-season state →</a></section></aside></div>'''
doc('games','Games',games)
baseline=next(x['homeBaselinePct'] for x in a['seasonWinRates'] if x['season']=='2025-26')
team_rows=[[x['abbreviation'],f'{x["restedWins"]} / {x["restedGames"]}',f'{x["restedWinPct"]:.1f}%',f'{x["tiredWins"]} / {x["tiredGames"]}',f'{x["tiredWinPct"]:.1f}%',sign(x['swing'])] for x in s['teams']]
lookup={x['teamId']:x['abbreviation'] for x in s['teams']}
calls=''.join(f'<div class="call"><span class="small muted">{x["date"]}</span><b>{lookup[x["awayTeamId"]]} @ {lookup[x["homeTeamId"]]}</b><span class="num">{x["awayScore"]}–{x["homeScore"]}</span><span class="small">Rested team <b>{"won" if x["restedTeamWon"] else "lost"}</b><br><span class="mono">RA {x["restAdvantage"]:.2f}</span></span></div>' for x in s['loudestCalls'][:5])
season=head('Season Report','What happened when teams arrived with different rest conditions.','Completed games · results')+f'''<section class="two section"><div><div class="eyebrow">Rested team at home · win rate</div><div class="big num metric">{s['overall']['winPct']}%</div><p><span class="tired">{sign(s['overall']['winPct']-baseline)} percentage points</span> versus this season’s {baseline}% home baseline.</p><p class="caption">{fmt(s['overall']['games'])} games · uncertainty ±{s['overall']['band']:.1f} percentage points.<br>{fmt(s['completedGames'])} / {fmt(s['scheduledGames'])} regular-season games completed.</p></div><div class="panel"><h3>The result is close to home court alone.</h3><p class="muted" style="margin-top:12px">The observed difference is small relative to the uncertainty. This record does not isolate the effect of rest.</p><p style="margin-top:20px"><a href="http://localhost:3110/analysis">Compare with the full historical record →</a></p></div></section><section class="section"><div class="section-head"><h2>Team results under different rest conditions</h2></div><p class="muted">Rested-at-home and tired-on-the-road records. Read each difference against the league’s {s['swingBaseline']:+.1f}-point comparison, not zero. These are records, not a ranking of fatigue management.</p><p class="caption">All 30 teams · ordered by observed difference</p>'''+table(['Team','Rested wins / games','Win %','Tired wins / games','Win %','Difference · pp'],team_rows[:6])+disclosure('Show the other 24 teams',table(['Team','Rested W / G','Win %','Tired W / G','Win %','Difference · pp'],team_rows[6:]))+'''</section><section class="section"><h2>When the rest gap was widest</h2><p class="caption">Five largest completed-game rest gaps, regardless of outcome. Rest advantage is a model-score difference.</p>'''+calls+'''<p class="caption"><a href="games.html">Browse matchup details →</a></p></section><section class="section"><p>Looking for travel, dense stretches, or favorable schedules? <a href="schedule.html">See Schedule Edge →</a></p></section>'''
doc('season','Season Report',season)
rank=''
for i,x in enumerate(q['teams']):
 v=x['netEdgeGames'];w=abs(v)/21*50;rank+=f'<div class="rank-row"><span class="muted mono">{i+1:02}</span><b>{x["abbreviation"]}</b><span class="diverge"><i style="width:{w}%;left:{50 if v>=0 else 50-w}%;background:var({"--rest" if v>=0 else "--tired"})"></i></span><b class="num {"rest" if v>=0 else "tired"}">{v:+d}</b></div>'
work=sorted(s['teams'],key=lambda x:-x['travelMiles'])
weeks=''.join(f'<div style="height:{x["avgFatigue"]/8*100}%" title="Week {x["week"]}: {x["avgFatigue"]}"></div>' for x in s['weeks'])
schedule=head('Schedule Edge','The demands of the calendar—and the rest advantages between opponents.','Team schedules · demands & advantages')+f'''<section class="section"><div class="section-head"><h2>Who had the favorable matchups?</h2><span class="small muted">Favorable − unfavorable games</span></div><div class="two"><p class="muted">Utah had <b class="rest">+21</b> net edge games; Boston had <b class="tired">−17</b>. Each row compares a team with its opponents.</p><p class="small muted">Final measured comparison · {fmt(q['league']['countedGames'])} of {fmt(q['scheduledGames'])} games. Positive is favorable; negative is unfavorable.</p></div><div class="ranking" style="margin-top:24px">{rank}</div>'''+disclosure('Show full matchup-advantage breakdown',table(['Team','Favorable','Unfavorable','Net games','Worth · wins'],[[x['abbreviation'],x['favorableGames'],x['unfavorableGames'],x['netEdgeGames'],sign(x['scheduleValueWins'])] for x in q['teams']])+'<p class="caption">Worth converts historical rest-group differences into win equivalents. It is descriptive, not wins caused by the schedule.</p>')+'''</section><section class="section"><div class="section-head"><h2>Travel and workload</h2><span class="eyebrow">Completed games only</span></div><p class="muted">A demanding schedule and an unfavorable matchup are different things. These counts describe the workload itself.</p>'''+table(['Team','Estimated miles','Back-to-backs','3 in 4'],[[x['abbreviation'],fmt(x['travelMiles']),x['backToBacks'],x['threeInFours']] for x in work[:5]])+disclosure('Compare all 30 teams',table(['Team','Estimated miles','Back-to-backs','3 in 4'],[[x['abbreviation'],fmt(x['travelMiles']),x['backToBacks'],x['threeInFours']] for x in work[5:]]))+f'''</section><section class="section"><h2>How workload changed through the season</h2><p class="caption">League-average modeled fatigue by week. Completed games only; not a projection. Scale: 0–8 model points.</p><div class="week-chart" aria-hidden="true">{weeks}</div><div class="week-labels"><span>Week 1</span><span>Week {len(s['weeks'])}</span></div>'''+disclosure('Read the weekly values',table(['Week beginning','Games','Mean fatigue'],[[x['startDate'],x['games'],x['avgFatigue']] for x in s['weeks']]))+'''</section><p><a href="methods.html">How schedule comparisons are calculated →</a></p>'''
doc('schedule','Schedule Edge',schedule)
rows=sorted([r for r in p['seasons'] if r[1]==2025 and r[5]>=300],key=lambda r:-r[5])[:20]
shoot=''
percent=lambda value:'—' if value is None else f'{value:.1f}'
for r in rows:
 delta=r[10]-r[8] if r[10] is not None and r[8] is not None else None
 name=e(p['names'][r[0]])
 shoot+=f'''<tr data-player="{e(p['names'][r[0]].lower())}" data-fga="{r[5]}" data-no-rest="{r[8] if r[8] is not None else ''}" data-rested="{r[10] if r[10] is not None else ''}" data-delta="{delta if delta is not None else ''}"><th scope="row"><a href="http://localhost:3110/shooting?player={r[0]}" class="player-link">{name}<small>{p['teams'][r[2]]}</small></a></th><td class="extra-col">{r[4]}</td><td class="extra-col">{fmt(r[5])}</td><td class="extra-col">{percent(r[6])}</td><td>{percent(r[8])}<small>{fmt(r[7])} att.</small></td><td>{percent(r[10])}<small>{fmt(r[9])} att.</small></td><td>{sign(delta) if delta is not None else '—'}</td></tr>'''
shoot_table='''<div class="dense-table-wrap"><table class="dense-shooting"><caption class="sr-only">Shooting by Rest: eFG percentages and shot attempts, 2025–26. Difference is 3+ days minus no rest, in percentage points.</caption><colgroup><col class="player-col"><col class="extra-col"><col class="extra-col"><col class="extra-col"><col class="split-col"><col class="split-col"><col class="delta-col"></colgroup><thead><tr><th scope="col">Player / team</th><th scope="col" class="extra-col">Games</th><th scope="col" class="extra-col" aria-sort="descending"><button data-sort="fga">Attempts <span aria-hidden="true">↓</span></button></th><th scope="col" class="extra-col">eFG%</th><th scope="col" aria-sort="none"><button data-sort="noRest">No rest<small>eFG%</small></button></th><th scope="col" aria-sort="none"><button data-sort="rested">3+ days<small>eFG%</small></button></th><th scope="col" aria-sort="none"><button data-sort="delta">Diff.<small>pp</small></button></th></tr></thead><tbody>'''+shoot+'''</tbody></table></div>'''
doc('shooting','Shooting by Rest','''<div class="dense-page">'''+head('Shooting by Rest','The same players, different amounts of rest. Compare rates with their attempts.','Player comparisons · eFG%',False)+'''<div class="dense-filters"><label>Season snapshot<select><option>2025–26</option></select></label><label class="search-label">Find a player<input id="player" type="search" placeholder="Search 20-player sample"></label><span class="small muted" id="player-count" role="status">20 players · most attempts first</span></div><p class="dense-key">No rest: played yesterday. 3+ days: at least three days since the player’s last appearance. <b>Diff.</b> = 3+ days minus no rest.</p>'''+shoot_table+'''<p id="no-players" hidden class="panel">No players match this 20-player sample. Clear search to show all 20.</p><div class="dense-footnote"><p class="muted">20 highest-volume player-season rows with at least 300 attempts. Regular season through Apr 12, 2026. Values are eFG%; “att.” means shot attempts.</p><p class="muted">A large difference can still be uncertain. These comparisons do not isolate the effect of rest. Career estimates pool attempts and shrink uncertain differences.</p><a class="button" href="http://localhost:3110/shooting">Open the complete player database →</a></div></div>''')
doc('shot','Expected Shot Value',head('Expected Shot Value','Compare estimated shooting efficiency by court location.','Other studies · location model')+'''<div class="toolbar"><button id="compare" aria-pressed="false">Compare models</button><span class="small muted">Captured 2025–26 baseline court · real source cells</span></div><div class="court-layout"><section><h2>Zone baseline</h2><p class="caption">Color: expected eFG%. Marker size: attempts.</p><img src="data/court.svg" alt="NBA half-court baseline shot-value map from the current application"><div class="court-note"><p>Live touch and keyboard inspection is available in the application.</p><a href="http://localhost:3110/shot-quality">Inspect a court location →</a></div></section><section id="model-comparison" hidden><h2>Location model</h2><p class="caption">Same locations · coordinate-based model.</p><img src="data/court-model.svg" alt="NBA half-court location-model shot-value map from the current application"><div class="court-note">Both courts show the same observed shot locations; their expected values use different models.</div></section></div><p class="caption">Location alone does not describe defenders, contest level, or the shot clock.</p>''')
methods=head('Rest advantage','The calculation, its evidence, and what it cannot tell us.','Behind the Data',False)+'''<div class="read-layout"><nav class="contents" aria-label="On this page"><div class="eyebrow">On this page</div><a href="#question">The question</a><a href="#baseline">The comparison</a><a href="#inputs">Model inputs</a><a href="#limits">Limits</a></nav><div class="reading"><section id="question"><h2>The question</h2><p>Among completed regular-season games, did the more-rested team win? The headline counts games where the rested team played at home and compares its win rate with the home-team baseline.</p></section><section id="baseline"><h2>Read against home court</h2><p>Home teams already win more often. A raw win rate for rested home teams includes that advantage. The displayed difference subtracts the relevant venue baseline.</p><p>A selected season uses its own home baseline. Historical results use the baseline for the historical sample.</p></section><section id="inputs"><h2>What enters the fatigue score</h2><p>Recent workload, estimated venue-to-venue travel, time-zone terms, back-to-backs, altitude, and schedule density contribute to the score. Extended rest and overtime are also included.</p><p>The score is a model, not a direct measurement of a player’s physical fatigue.</p><a href="http://localhost:3110/behind-the-data/rest-advantage">Read the full formula and coefficient history →</a></section><section id="limits"><h2>What this cannot establish</h2><p>These comparisons do not isolate rest from team strength and other differences between the groups. A rest advantage is not a guarantee about one game.</p><p>Missing measurements remain missing. They are not displayed as zero fatigue or zero effect.</p></section><a href="explore.html">Other methods and studies →</a></div></div>'''
doc('methods','Behind the Data',methods)
explore=head('Explore','Rest-related questions first, with other basketball studies alongside.','Findings & evidence',False)
for title,items in [('Rest and fatigue',[('shooting.html','Player Shooting','Do players shoot differently with more rest?'),('http://localhost:3110/playoffs','Playoff Rest','How does prior-round workload relate to a series?'),('http://localhost:3110/analysis','Model Results','How does the rest model compare with history?')]),('Other studies',[('http://localhost:3110/availability','Availability Cost','What do historical absences tell us?'),('http://localhost:3110/officiating','Officiating','What did the NBA identify in close-game endings?'),('shot.html','Shot Value','How does expected efficiency vary around the court?')]),('Research',[('methods.html','Behind the Data','Sources, calculations, and limitations.'),('http://localhost:3110/behind-the-data/referees/archive','Referee research archive','Historical foul patterns and folklore comparisons.')])]:
 explore+=f'<section class="section"><h2>{title}</h2><div class="explore-list" style="margin-top:20px">'+''.join(f'<a href="{url}"><h3>{label} →</h3><small>{desc}</small></a>' for url,label,desc in items)+'</div></section>'
doc('explore','Explore',explore)
doc('about','About FullCourt',head('FullCourt','Rest is the starting question. Evidence is the standard.','About',False)+'''<section class="section reading"><h2>What the name means</h2><p>FullCourt connects the basketball floor with a place where claims are examined. The project pairs findings with comparison groups, sample sizes, and limitations.</p><p>Rest, travel and schedule density remain its central questions. Other basketball studies remain available through Explore.</p><p><a href="home.html">Back to the findings →</a></p></section>''')
doc('states','Scope examples',head('Season scope examples','Review-only states; no upcoming values are fabricated.','Design review',False)+'''<section class="section" id="upcoming"><h2>2026–27 · published schedule</h2><p class="muted">[UPCOMING SCHEDULE SNAPSHOT NOT BUNDLED]</p><p>In the application, this action should open the published next-season schedule. Any rest-edge projections must be separately labeled and supported by available inputs.</p></section><section class="section"><h2>Season Report · awaiting results</h2><p>No completed games in the selected season. Results appear after games are played.</p><div class="toolbar"><a class="button" href="season.html">Read the previous season report</a><a class="button" href="#upcoming">View upcoming schedule</a></div></section>''')
index=head('FullCourt design review','One coordinated direction, shown across seven representative pages. Resize any page to compare desktop and mobile.','Rest-focused redesign',False)
index+='<p style="margin-bottom:24px"><a class="button primary" href="review.html">Open desktop / mobile review viewer →</a></p><div class="explore-list">'+''.join(f'<a href="{slug}.html"><h2>{name} →</h2><small>{description}</small></a>' for slug,name,description in [('home','Homepage','Rest finding, schedule comparison, shooting question.'),('games','Games','Matchups first; rest gap visible on a phone.'),('season','Season Report','Completed outcomes, team records, notable games.'),('schedule','Schedule Edge','Relative advantages, demands, workload calendar.'),('shooting','Player Shooting','Compact comparisons with both sample sizes.'),('shot','Shot Value','Single court and explicit comparison action.'),('methods','Behind the Data','Anchored reading with an on-page contents list.')])+'</div><section class="section"><h2>Review these decisions</h2><p>Does the homepage establish the rest/fatigue focus? Can Games be scanned quickly? Are Season Report and Schedule Edge clearly different? Can mobile readers interpret shooting comparisons without sideways scrolling?</p><p class="caption">Supporting routes: <a href="explore.html">Explore</a> · <a href="about.html">About</a> · <a href="states.html">Season scope states</a>. Charts, tables and labels use bundled real snapshots except explicitly marked placeholders. Existing-application links require localhost:3110.</p></section>'
doc('index','Mockup review',index)

import runpy
runpy.run_path(str(P/"build-colors.py"), init_globals={"shooting_source": (P/"shooting.html").read_text()})
