import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  AVAILABILITY_BEST_OUT_BY_SEASON,
  AVAILABILITY_DEFINITION,
  AVAILABILITY_EFFECTS,
  AVAILABILITY_FREQUENCY,
  AVAILABILITY_NOISE,
  AVAILABILITY_SAMPLE,
  AVAILABILITY_SCHEDULE_HOLDS_UP,
} from "@/lib/availability-facts";

/**
 * These constants are the availability surface's published numbers. They are generated by
 * `ml/availability_facts.py` and hand-mirrored into `availability-facts.ts`, so this test is
 * what stops the two drifting apart — a figure edited in a component and nowhere else is
 * exactly the failure this file exists to prevent.
 */
const facts = JSON.parse(
  readFileSync(join(process.cwd(), "ml", "availability_facts.json"), "utf8")
);

describe("availability facts mirror the generated report", () => {
  it("the sample matches", () => {
    expect(AVAILABILITY_SAMPLE).toEqual(facts.sample);
  });

  it("the definition matches", () => {
    expect(AVAILABILITY_DEFINITION).toEqual(facts.definition);
  });

  it("the published effects match", () => {
    expect(AVAILABILITY_EFFECTS).toEqual(facts.effectsInPoints);
  });

  it("the frequencies match", () => {
    expect(AVAILABILITY_FREQUENCY).toEqual(facts.frequency);
  });

  it("the schedule-holds-up block matches", () => {
    expect(AVAILABILITY_SCHEDULE_HOLDS_UP).toEqual(facts.scheduleHoldsUp);
  });

  it("the noise block matches", () => {
    expect(AVAILABILITY_NOISE).toEqual(facts.noise);
  });

  it("every season's best-player-out rate matches", () => {
    expect(AVAILABILITY_BEST_OUT_BY_SEASON).toEqual(facts.seasonBestOutRate);
  });
});

describe("the claims the copy will rest on", () => {
  it("every published effect is distinguishable from zero", () => {
    for (const [name, effect] of Object.entries(AVAILABILITY_EFFECTS)) {
      expect(Math.abs(effect.t), `${name} must clear |t| >= 2`).toBeGreaterThanOrEqual(2);
    }
  });

  it("losing the best player is worth about what home court is", () => {
    // The page's headline sentence. If a re-run moves these apart, the copy is wrong and
    // this is where that gets caught rather than in review.
    const gap = Math.abs(
      AVAILABILITY_EFFECTS.bestPlayerOut.points - AVAILABILITY_EFFECTS.homeCourt.points
    );
    expect(gap).toBeLessThan(0.5);
  });

  it("load management does not explain the schedule effects away", () => {
    // The defensive claim: if any schedule term moved by a lot once absence is controlled,
    // "your back-to-back result is really load management" would become the honest reading.
    for (const [name, term] of Object.entries(AVAILABILITY_SCHEDULE_HOLDS_UP)) {
      expect(Math.abs(term.shiftPct), `${name} shifted more than 15%`).toBeLessThan(15);
    }
  });

  it("the season trend runs from rare to common", () => {
    const first = AVAILABILITY_BEST_OUT_BY_SEASON[0]!;
    const last = AVAILABILITY_BEST_OUT_BY_SEASON.at(-1)!;
    expect(last.rate).toBeGreaterThan(first.rate * 2);
  });

  it("the noise block keeps the page honest about explanatory power", () => {
    // Residual margin stays close to the raw spread: these effects are real but small next
    // to how much of a basketball game is noise. Copy must not imply otherwise.
    expect(AVAILABILITY_NOISE.rmseWithAbsence).toBeGreaterThan(
      AVAILABILITY_NOISE.marginStdDev * 0.85
    );
  });
});
