import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  PLAYOFF_BEST_OF_FIVE,
  PLAYOFF_ENTRY_REST_BUCKETS,
  PLAYOFF_EQUAL_REST,
  PLAYOFF_GRIND_EXOGENOUS,
  PLAYOFF_GRIND_MATRIX,
  PLAYOFF_MODEL_COEFFICIENTS,
  PLAYOFF_MODEL_INTERCEPT,
  PLAYOFF_ROUND_SPLIT,
  PLAYOFF_ROUNDS_TWO_PLUS_RECORD,
} from "@/lib/playoff-rest-facts";
import { PLAYOFF_MODEL_ACCURACY, PLAYOFF_MODEL_CALIBRATION } from "@/lib/playoff-model-metrics";

/**
 * These constants are the page's published numbers. They are generated by
 * `ml/playoff_rest_report.py` and hand-mirrored here, so this test is the thing that stops
 * the two drifting apart — a figure edited in a component and nowhere else is exactly the
 * failure mode this file exists to prevent.
 */
const facts = JSON.parse(
  readFileSync(join(process.cwd(), "ml", "playoff_rest_facts.json"), "utf8")
);

const roundSplit = JSON.parse(
  readFileSync(join(process.cwd(), "ml", "playoff_round_split.json"), "utf8")
);

describe("playoff rest facts mirror the generated report", () => {
  it("equal-rest counts match", () => {
    expect(PLAYOFF_EQUAL_REST).toEqual(facts.equalRest);
  });

  it("the grind matrix matches", () => {
    expect(PLAYOFF_GRIND_MATRIX).toEqual(facts.grindMatrix);
  });

  it("the exogenous block matches", () => {
    expect(PLAYOFF_GRIND_EXOGENOUS).toEqual(facts.exogenous);
  });

  it("the entry-rest buckets match", () => {
    expect(PLAYOFF_ENTRY_REST_BUCKETS).toEqual(facts.entryRestBuckets);
  });

  it("the best-of-five context matches", () => {
    expect(PLAYOFF_BEST_OF_FIVE.round1BestOfFive).toBe(facts.bestOfFiveRound1Series);
    expect(PLAYOFF_BEST_OF_FIVE.round1Total).toBe(facts.round1TotalSeries);
  });

  it("the round split matches the generated report", () => {
    expect(PLAYOFF_ROUND_SPLIT.roundsTwoPlus).toEqual(roundSplit.roundsTwoPlus);
    expect(PLAYOFF_ROUND_SPLIT.roundOne).toEqual(roundSplit.roundOne);
  });

  it("the paired record matches the generated report", () => {
    expect(PLAYOFF_ROUNDS_TWO_PLUS_RECORD).toEqual(roundSplit.roundsTwoPlusRecord);
  });

  it("the model coefficients match the generated report", () => {
    expect(PLAYOFF_MODEL_COEFFICIENTS).toEqual(roundSplit.coefficients);
    expect(PLAYOFF_MODEL_INTERCEPT).toBe(roundSplit.intercept);
  });

  it("the pooled win/tie/loss record matches the generated report", () => {
    const { win, tie, loss } = roundSplit.pooledRecord;
    expect(PLAYOFF_MODEL_ACCURACY.winTieLoss).toBe(`${win}/${tie}/${loss}`);
  });

  it("the pooled accuracy matches the generated report", () => {
    // The JSON stores percentages (0-100), the constant stores fractions (0-1). toBeCloseTo
    // rather than toBe: dividing by 100 introduces binary floating-point noise (e.g.
    // 74.4 / 100 !== 0.744 under strict equality) that isn't a real numeric discrepancy.
    expect(PLAYOFF_MODEL_ACCURACY.model).toBeCloseTo(roundSplit.pooled.accuracy / 100, 10);
    expect(PLAYOFF_MODEL_ACCURACY.baseline).toBeCloseTo(
      roundSplit.pooled.baselineAccuracy / 100,
      10
    );
  });

  it("the calibration table matches the generated report", () => {
    const logLoss = PLAYOFF_MODEL_CALIBRATION.find((m) => m.key === "logLoss")!;
    expect(logLoss.model).toBe(roundSplit.pooled.logLoss);
    expect(logLoss.baseline).toBe(roundSplit.pooled.baselineLogLoss);

    const brier = PLAYOFF_MODEL_CALIBRATION.find((m) => m.key === "brier")!;
    expect(brier.model).toBe(roundSplit.pooled.brier);
    expect(brier.baseline).toBe(roundSplit.pooled.baselineBrier);
  });

  it("each calibration improvementPct is the relative reduction vs baseline", () => {
    for (const entry of PLAYOFF_MODEL_CALIBRATION) {
      expect(entry.improvementPct).toBe(
        Math.round(((entry.baseline - entry.model) / entry.baseline) * 100)
      );
    }
  });
});

describe("the claims the page makes are actually true of the data", () => {
  it("every playoff game after game 1 is on equal rest", () => {
    // Section A's headline is an exact claim, not a rounded one. If this ever fails the
    // section is false and must not ship.
    expect(PLAYOFF_EQUAL_REST.laterEqual).toBe(PLAYOFF_EQUAL_REST.laterGames);
    expect(PLAYOFF_EQUAL_REST.laterGames).toBeGreaterThan(2000);
  });

  it("game 1 is where the asymmetry lives", () => {
    expect(PLAYOFF_EQUAL_REST.game1Equal).toBeLessThan(PLAYOFF_EQUAL_REST.game1Games);
  });

  it("the fresh-vs-tired cell is the highest in the matrix", () => {
    const { ownLowOppHigh, ownLowOppLow, ownHighOppLow, ownHighOppHigh } = PLAYOFF_GRIND_MATRIX;
    for (const other of [ownLowOppLow, ownHighOppLow, ownHighOppHigh]) {
      expect(ownLowOppHigh.winPct).toBeGreaterThan(other.winPct);
    }
  });

  it("the effect survives the strength control", () => {
    expect(PLAYOFF_GRIND_EXOGENOUS.closeMatchupOppWentLong.winPct).toBeGreaterThan(
      PLAYOFF_GRIND_EXOGENOUS.closeMatchupOppClosedEarly.winPct
    );
  });

  it("the model beats the one-line rule in rounds 2+ and loses in round 1", () => {
    // Section D publishes both halves. If either direction flips, the section's copy is wrong.
    expect(PLAYOFF_ROUND_SPLIT.roundsTwoPlus.model).toBeGreaterThan(
      PLAYOFF_ROUND_SPLIT.roundsTwoPlus.baseline
    );
    expect(PLAYOFF_ROUND_SPLIT.roundOne.model).toBeLessThan(PLAYOFF_ROUND_SPLIT.roundOne.baseline);
  });

  it("the paired record is a majority of decided seasons", () => {
    const { win, loss } = PLAYOFF_ROUNDS_TWO_PLUS_RECORD;
    expect(win).toBeGreaterThan(loss);
  });
});
