import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  HOME_BAR_COUNTERFACTUAL,
  liftOverBaseline,
  RESTED_AT_HOME,
  RESTED_ON_ROAD,
  REST_SPLIT_BASELINE,
  REST_SPLIT_SAMPLE,
} from "@/lib/rest-split-facts";

/**
 * These constants are what the method page publishes. They are generated by
 * `scripts/measure_uncalled_half.ts` and hand-mirrored into `rest-split-facts.ts`, so this
 * test is what stops the two drifting apart.
 *
 * It is the guard the page did not have. "44.4% across 7,224 games" sat in prose describing a
 * population the site had stopped publishing, and nothing failed.
 */
const facts = JSON.parse(
  readFileSync(join(process.cwd(), "ml", "rest_split_facts.json"), "utf8")
);

describe("rest split facts mirror the generated measurement", () => {
  it("the sample matches", () => {
    expect(REST_SPLIT_SAMPLE).toEqual(facts.sample);
  });

  it("the venue baseline matches", () => {
    expect(REST_SPLIT_BASELINE).toEqual(facts.baseline);
  });

  it("the rested-at-home row matches, ladder included", () => {
    expect(RESTED_AT_HOME).toEqual(facts.restedAtHome);
  });

  it("the rested-on-road row matches, ladder included", () => {
    expect(RESTED_ON_ROAD).toEqual(facts.restedOnRoad);
  });

  it("the home-bar counterfactual matches", () => {
    expect(HOME_BAR_COUNTERFACTUAL).toEqual(facts.counterfactual);
  });
});

describe("the home-bar counterfactual", () => {
  /**
   * The load-bearing fact: folding home court into the score and letting it pick lands BELOW
   * simply backing the home team every time. If this ever flips, the argument for counting the
   * two rows separately needs rewriting rather than restating.
   */
  it("does not beat picking the home team in every game", () => {
    expect(HOME_BAR_COUNTERFACTUAL.accuracyPct).toBeLessThan(
      HOME_BAR_COUNTERFACTUAL.alwaysHomePct
    );
  });

  it("still makes road picks, and loses most of them", () => {
    const { roadCalls, roadLosses } = HOME_BAR_COUNTERFACTUAL;

    expect(roadCalls).toBeGreaterThan(0);
    expect(roadLosses / roadCalls).toBeGreaterThan(0.5);
  });

  it("uses the whole population, so its coverage is not comparable to a decided-only rate", () => {
    expect(HOME_BAR_COUNTERFACTUAL.calls).toBeGreaterThan(REST_SPLIT_SAMPLE.decided);
    expect(HOME_BAR_COUNTERFACTUAL.calls).toBeLessThanOrEqual(REST_SPLIT_SAMPLE.scoredGames);
  });
});

describe("rest split facts are internally consistent", () => {
  it("the two rows account for every decided game", () => {
    expect(RESTED_AT_HOME.games + RESTED_ON_ROAD.games).toBe(REST_SPLIT_SAMPLE.decided);
  });

  it("every scored game is decided or neutral, and nothing is both", () => {
    expect(REST_SPLIT_SAMPLE.decided + REST_SPLIT_SAMPLE.neutral).toBe(
      REST_SPLIT_SAMPLE.scoredGames
    );
  });

  it("the baseline covers the whole population, not only the published row", () => {
    // The point of the baseline: it is the widest set, wider than either row.
    expect(REST_SPLIT_BASELINE.games).toBe(REST_SPLIT_SAMPLE.scoredGames);
    expect(REST_SPLIT_BASELINE.games).toBeGreaterThan(RESTED_AT_HOME.games);
  });

  it("states both venue baselines from the same counts", () => {
    const { games, homeWins, homeWinPct, roadWinPct } = REST_SPLIT_BASELINE;
    expect(homeWinPct).toBe(Math.round((homeWins / games) * 1000) / 10);
    expect(roadWinPct).toBe(Math.round(((games - homeWins) / games) * 1000) / 10);
  });

  it("keeps each ladder cumulative, so a wider gap is never a larger sample", () => {
    for (const row of [RESTED_AT_HOME, RESTED_ON_ROAD]) {
      for (let i = 1; i < row.ladder.length; i++) {
        expect(row.ladder[i].games).toBeLessThanOrEqual(row.ladder[i - 1].games);
      }
      expect(row.ladder[0].games).toBeLessThanOrEqual(row.games);
    }
  });

  it("keeps every rung's win count inside its own sample", () => {
    for (const row of [RESTED_AT_HOME, RESTED_ON_ROAD]) {
      for (const rung of row.ladder) {
        expect(rung.wins).toBeLessThanOrEqual(rung.games);
      }
    }
  });
});

/**
 * The two claims the page published that the measurement refuted. Pinned as tests so the
 * sentences cannot come back without the data coming back with them.
 */
describe("the claims that had to be retired", () => {
  it("a rest gap DOES lift the road row past even, so 'no threshold rescues it' is false", () => {
    const rescued = RESTED_ON_ROAD.ladder.filter((r) => r.winPct >= 50);

    expect(rescued.length).toBeGreaterThan(0);
    expect(rescued.map((r) => r.gap)).toEqual([6, 7]);
  });

  it("the home row's gain stops growing, so it does not 'compound at the extremes'", () => {
    const byGap = new Map(RESTED_AT_HOME.ladder.map((r) => [r.gap, r.winPct]));

    // 65.3 → 65.2 → 65.9 across gaps 5, 6, 7: flat, and non-monotonic.
    expect(byGap.get(6)!).toBeLessThan(byGap.get(5)!);
    expect(Math.abs(byGap.get(7)! - byGap.get(5)!)).toBeLessThan(1);
  });
});

describe("liftOverBaseline", () => {
  it("signs the distance from the side's own baseline", () => {
    expect(liftOverBaseline(RESTED_AT_HOME.winPct, REST_SPLIT_BASELINE.homeWinPct)).toBe(1.3);
    expect(liftOverBaseline(RESTED_ON_ROAD.winPct, REST_SPLIT_BASELINE.roadWinPct)).toBe(2.3);
  });

  it("keeps one decimal rather than leaking float error", () => {
    expect(liftOverBaseline(63.1, 59.9)).toBe(3.2);
    expect(liftOverBaseline(63.1, 59.9).toString()).toBe("3.2");
  });
});
